### ISSUE TITLE
Unable to list/search manga using Mangadex extension

### ISSUE THREAD

**Issue by valderman** [faldez/tanoshi-extensions#11]
Steps to reproduce:
* Run official tanoshi 0.13.0 binary
* Install mangadex plugin from catalogue -> available
* Go to catalogue -> mangadex
* (Optional) search for a title you know to be present on mangadex

Expected result:
* At least one title is listed

Actual result:
* No titles are listed, response from tanoshi backend is `{"mangas":[],"status":"Empty"}`

**Comment by faldez** [comment]
mangadex require you to login for search, you can login using top right icon at /catalogue/mangadex

**Comment by valderman** [comment]
Oops, you're right. That's silly of me.
