### ISSUE TITLE
[local] Erroneous sorting for filenames that include volume and chapter number.

### ISSUE THREAD

**Issue by eridanired123** [faldez/tanoshi-extensions#3]
If a title has volume numbers superseded by chapter numbers, local plugin will pass the volume number as if it were the file chapter number.

For example for files named `Aiura Volume 01 Chapter 001` and `Aiura Volume 01 Chapter 002` both will be considered Chapter 1 and will be listed as `Ch. 01 - Aiura Volume 01 Chapter 001` and  `Ch. 01 - Aiura Volume 01 Chapter 002` respectively. Things get really weird at the bottom of the example screenshots below.

It should be sorted alphabetically in most scenarios.

![Instantánea de el 20|06|30 a las 21:53:54 hrs](https://user-images.githubusercontent.com/41547329/86197990-3cb20700-bb1c-11ea-97c5-0579d9a8c26a.png)

![Captura de pantalla 2020-06-30 - 22 00 08-fullpage](https://user-images.githubusercontent.com/41547329/86198403-2d7f8900-bb1d-11ea-9c9a-b4d68dfd963c.png)

_______
tanoshi-linux v0.7.0

**Comment by faldez** [comment]
this should be fixed now
