### ISSUE TITLE
Maganelo (js working js extension exemple to help)

### ISSUE THREAD

**Issue by BirdInFire** [faldez/tanoshi-extensions#33]
hello i do know javascript but not the language behind these extension, does anyone know this language to translate this extension : https://github.com/hkalexling/mango-plugins/tree/master/plugins/manganelo from mango ?

Thanks if anyone can do it ;)

**Comment by faldez** [comment]
hmm manganelo redirect me to manganato, and it seems it use the same layout as mangakalot. might be able to tackle #9 too. I'll look into it

**Comment by BirdInFire** [comment]
> hmm manganelo redirect me to manganato, and it seems it use the same layout as mangakalot. might be able to tackle #9 too. I'll look into it

If it was a languages i know i will have PR the translation, since tanoshi is the only one who let me read it before download ^^) ( and the manga i read have more than 100 chapter behind on mangadex :/).

So many thanks (if you have the time to do it)

**Comment by faldez** [comment]
There is alternative such as https://github.com/AdollaApp/Adolla. It says it supports manganelo. You can use that if you can't wait

**Comment by BirdInFire** [comment]
> There is alternative such as https://github.com/AdollaApp/Adolla that let you read without download. It says it supports manganelo. You can use that if you can't wait

no problem will check (but if i can do a proposition) is that you actually create a template of one of the already done lib.rs with mant comment, like that people like me who start rust, can help (without having to try decipher what command do what to try to help).  ;)

**Comment by faldez** [comment]
I plan to write docs to write extension, but I haven't stabilized the API yet. Will do once I stabilized the extension API

**Comment by BirdInFire** [comment]
> There is alternative such as https://github.com/AdollaApp/Adolla that let you read without download. It says it supports manganelo. You can use that if you can't wait

i have tried Adolla not work properly (their search do not work do not know if it's my fault or their (reinstalled it 3 times)), so will wait for your (better anyway)^^

**Comment by faldez** [comment]
it my take a while, I want to stabilize the api, before I write another extension. hopefully this month

**Comment by faldez** [comment]
@BirdInFire I've added mangakakalot and manganato, please check them out.

**Comment by BirdInFire** [comment]
> @BirdInFire I've added mangakakalot and manganato, please check them out.

The time to go to my main computer and restart my docker and i try that.

Thanks

**Comment by BirdInFire** [comment]
@faldez work like a charm many thanks

**Comment by BirdInFire** [comment]
After some more test have seen that "next chapter" always return "no next chapter" even when there are and even when downloaded.

**Comment by faldez** [comment]
hmm I think I need server update to solve this, might take a while

**Comment by faldez** [comment]
turns out I don't need to. I pushed a fix, please check them out

**Comment by BirdInFire** [comment]
> turns out I don't need to. I pushed a fix, please check them out. you need to refresh the chapters in manga page

it's indeed fixed thanks i'm closing :)
