### ISSUE TITLE
mangakalot extension

### ISSUE THREAD

**Issue by faldez** [faldez/tanoshi-extensions#9]

**Comment by BirdInFire** [comment]
@faldez for this one when trying to install it from source it generate : installSource:2:3: /tanoshi/plugins/mangakalot.so: file too short error .

**Comment by faldez** [comment]
Let me check later

**Comment by BirdInFire** [comment]
> Let me check later

no problem the two are nearly (or are do not really know) in sync, just noted it, so you can check later.

**Comment by faldez** [comment]
mangakakalot works fine when built from local but throw error when built from ci, weird

**Comment by faldez** [comment]
alright it's fixed
